"""Provider-agnostic market data domain.

Market data answers what quote/chain data was available from a quote provider.
It is intentionally separate from broker sync, which answers what a brokerage
account holds. Every market quote snapshot must carry provider, timestamp,
data mode, freshness, and actionability metadata so downstream risk services
cannot silently treat stale or manual data as immediately actionable.
"""

from app.services.market_data.freshness import (
    DEFAULT_MAX_QUOTE_AGE_SECONDS,
    QuoteFreshnessDecision,
    classify_quote_actionability,
    classify_quote_freshness,
    evaluate_quote_freshness,
    quote_age_seconds,
)
from app.services.market_data.models import (
    ACTIONABILITY_STATUSES,
    CONTRACT_SUPPORT_STATUSES,
    DATA_MODES,
    FRESHNESS_STATUSES,
    GREEKS_SOURCES,
    IMPLIED_VOLATILITY_SOURCES,
    MARKET_FRESHNESS_SCOPE,
    MARKET_COVERAGE_STATUSES,
    MARKET_METRIC_SOURCES,
    OPTION_CHAIN_FRESHNESS_SCOPE,
    OPTION_QUOTE_FRESHNESS_SCOPE,
    OPTION_TYPES,
    UNDERLYING_QUOTE_FRESHNESS_SCOPE,
    ActionabilityStatus,
    ContractSupportStatus,
    DataMode,
    FreshnessStatus,
    GreeksSource,
    ImpliedVolatilitySource,
    MarketDataFreshnessScope,
    MarketCoverageStatus,
    MarketMetricSource,
    OptionChainSnapshot,
    OptionContractIdentity,
    OptionQuoteSnapshot,
    OptionType,
    ProviderCapabilities,
    QuoteRequestContext,
    StockQuoteSnapshot,
    UnderlyingQuoteSnapshot,
)
from app.services.market_data.snapshots import (
    MarketDataSnapshotReference,
    ReportMarketDataSnapshot,
    SnapshotKind,
    SnapshotPurpose,
    freeze_report_market_inputs,
    option_chain_snapshot_reference,
    option_quote_snapshot_reference,
    stock_quote_snapshot_reference,
)
from app.services.market_data.interfaces import (
    GreeksProvider,
    MarketDataProvider,
    OptionDataProvider,
)
from app.services.market_data.manual_provider import (
    ManualMarketDataNotFoundError,
    ManualMarketDataProvider,
    build_manual_option_quote,
    build_manual_stock_quote,
)
from app.services.market_data.alpaca_evaluation_provider import (
    ALPACA_BASIC_EVALUATION_PROVIDER,
    AlpacaBasicEvaluationProvider,
    AlpacaEvaluationClient,
)
from app.services.market_data.eod_history import (
    DEFAULT_EOD_HISTORY_LIMIT,
    FMP_EOD_CAVEAT_CODE,
    FMP_EOD_HISTORY_URL,
    FMP_EOD_SOURCE_KEY,
    FMP_EOD_SOURCE_LABEL,
    FMP_EOD_UNAVAILABLE_CAVEAT_CODE,
    FrozenEodHistoryWindow,
    FmpEodHistoryClient,
    FmpEodHistoryError,
    FmpEodHistoryHttpClient,
    FmpEodHistorySubscriptionRequiredError,
    MarketContextExecutionContext,
    MarketContextPolicy,
    MarketContextRequestBudget,
    MarketContextSnapshot,
    build_market_context_snapshot,
    default_market_context_execution_context,
    get_market_context_snapshot,
    get_frozen_eod_history_window,
    market_context_execution_context_for_client,
    market_context_policy_from_environment,
    normalize_eod_history_rows,
)

__all__ = [
    "ACTIONABILITY_STATUSES",
    "ALPACA_BASIC_EVALUATION_PROVIDER",
    "CONTRACT_SUPPORT_STATUSES",
    "DATA_MODES",
    "DEFAULT_MAX_QUOTE_AGE_SECONDS",
    "FRESHNESS_STATUSES",
    "FMP_EOD_CAVEAT_CODE",
    "FMP_EOD_HISTORY_URL",
    "FMP_EOD_SOURCE_KEY",
    "FMP_EOD_SOURCE_LABEL",
    "FMP_EOD_UNAVAILABLE_CAVEAT_CODE",
    "GREEKS_SOURCES",
    "IMPLIED_VOLATILITY_SOURCES",
    "MARKET_FRESHNESS_SCOPE",
    "MARKET_COVERAGE_STATUSES",
    "MARKET_METRIC_SOURCES",
    "OPTION_CHAIN_FRESHNESS_SCOPE",
    "OPTION_QUOTE_FRESHNESS_SCOPE",
    "OPTION_TYPES",
    "UNDERLYING_QUOTE_FRESHNESS_SCOPE",
    "ActionabilityStatus",
    "AlpacaBasicEvaluationProvider",
    "AlpacaEvaluationClient",
    "ContractSupportStatus",
    "DataMode",
    "FreshnessStatus",
    "FmpEodHistoryClient",
    "FmpEodHistoryError",
    "FmpEodHistoryHttpClient",
    "FmpEodHistorySubscriptionRequiredError",
    "FrozenEodHistoryWindow",
    "GreeksProvider",
    "GreeksSource",
    "ImpliedVolatilitySource",
    "ManualMarketDataNotFoundError",
    "ManualMarketDataProvider",
    "MarketContextExecutionContext",
    "MarketContextPolicy",
    "MarketContextRequestBudget",
    "MarketContextSnapshot",
    "MarketDataProvider",
    "MarketDataFreshnessScope",
    "MarketCoverageStatus",
    "MarketMetricSource",
    "MarketDataSnapshotReference",
    "OptionChainSnapshot",
    "OptionContractIdentity",
    "OptionDataProvider",
    "OptionQuoteSnapshot",
    "OptionType",
    "ProviderCapabilities",
    "QuoteFreshnessDecision",
    "QuoteRequestContext",
    "ReportMarketDataSnapshot",
    "SnapshotKind",
    "SnapshotPurpose",
    "StockQuoteSnapshot",
    "UnderlyingQuoteSnapshot",
    "build_manual_option_quote",
    "build_manual_stock_quote",
    "build_market_context_snapshot",
    "classify_quote_actionability",
    "classify_quote_freshness",
    "default_market_context_execution_context",
    "evaluate_quote_freshness",
    "freeze_report_market_inputs",
    "get_market_context_snapshot",
    "get_frozen_eod_history_window",
    "market_context_execution_context_for_client",
    "market_context_policy_from_environment",
    "normalize_eod_history_rows",
    "option_chain_snapshot_reference",
    "option_quote_snapshot_reference",
    "quote_age_seconds",
    "stock_quote_snapshot_reference",
]
