import { useAccountContext } from "../../context/useAccountContext";
import { useReports } from "../../hooks/useReports";
import SectionCard from "../shared/SectionCard";
import Timestamp from "../shared/Timestamp";
import { LoadingSkeleton, ErrorState } from "../shared/StateViews";
import { type ReportThreadRead } from "../../types/api";
import ReportScopeSummary from "./ReportScopeSummary";

/**
 * ReportHistoryPlaceholder — Phase 11 report list wired to Phase 10 APIs.
 *
 * Design intent: this surface must visually communicate that this product has
 * an agentic analytical layer — not that it is just a portfolio viewer.
 * The empty state carries framing copy explaining what future reports contain.
 *
 * Phase 11 scope:
 * - Thread list (title, type, status, timestamp) — read-only.
 * - Empty state with agentic copilot framing.
 * - No message viewer, no agent step log, no "run agent" button (Phase 16).
 * - No TradingAgents UI.
 */
export default function ReportHistoryPlaceholder() {
  const { selectedUser } = useAccountContext();
  const { threads, status, error } = useReports(selectedUser?.id ?? null);

  return (
    <SectionCard
      id="report-history"
      label="Report History"
      headerRight={
        <span style={styles.agentBadge}>agentic copilot</span>
      }
    >
      {status === "loading" && (
        <LoadingSkeleton rows={3} label="Loading report history…" />
      )}
      {status === "error" && (
        <ErrorState message={error ?? "Unknown error"} />
      )}
      {status === "success" && threads.length === 0 && (
        <EmptyReports />
      )}
      {status === "success" && threads.length > 0 && (
        <ThreadList threads={threads} />
      )}
    </SectionCard>
  );
}

/* ── Empty state ────────────────────────────────────────────────────────── */

function EmptyReports() {
  return (
    <div style={styles.empty}>
      <span style={styles.emptyIcon} aria-hidden="true">⊙</span>
      <p style={styles.emptyTitle}>No reports yet</p>
      <p style={styles.emptyBody}>
        Analytical reports will appear here after the agent runs. Each report
        captures portfolio context, risk flags, and income candidates at a
        specific point in time — so you can review reasoning history alongside
        your broker data.
      </p>
      <p style={styles.emptyNote}>
        Reports are generated by the portfolio copilot agent. They are
        informational only and read-only. Market quote data and risk engine
        integration will be added in future phases.
      </p>
    </div>
  );
}

/* ── Thread list ────────────────────────────────────────────────────────── */

function ThreadList({ threads }: { threads: ReportThreadRead[] }) {
  const sorted = [...threads].sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );

  return (
    <div style={styles.list}>
      <p style={styles.listNote}>
        Reports are read-only snapshots. Scope shown below is the saved report scope, not the current account selector.
      </p>
      {sorted.map((t) => (
        <ThreadRow key={t.id} thread={t} />
      ))}
    </div>
  );
}

function ThreadRow({ thread }: { thread: ReportThreadRead }) {
  const statusCfg = statusConfig(thread.status);

  return (
    <div style={styles.row}>
      <div style={styles.rowLeft}>
        <p style={styles.rowTitle}>{thread.title}</p>
        <p style={styles.rowMeta}>
          {thread.report_type}
        </p>
        <ReportScopeSummary scope={thread.scope_metadata} compact />
      </div>
      <div style={styles.rowRight}>
        <span
          style={{
            ...styles.statusChip,
            color: statusCfg.color,
            borderColor: statusCfg.color,
          }}
          aria-label={`Status: ${thread.status}`}
        >
          {statusCfg.icon} {thread.status}
        </span>
        <Timestamp iso={thread.created_at} prefix="" />
      </div>
    </div>
  );
}

function statusConfig(status: string): { icon: string; color: string } {
  switch (status) {
    case "completed": return { icon: "●", color: "var(--color-live)" };
    case "running":   return { icon: "◑", color: "var(--color-accent)" };
    case "failed":    return { icon: "⚠", color: "var(--color-error)" };
    case "cancelled": return { icon: "○", color: "var(--color-text-muted)" };
    case "draft":
    default:          return { icon: "○", color: "var(--color-unknown)" };
  }
}

/* ── Styles ─────────────────────────────────────────────────────────────── */

const styles: Record<string, React.CSSProperties> = {
  agentBadge: {
    fontSize: "var(--font-size-xs)",
    color: "var(--color-accent)",
    backgroundColor: "var(--color-accent-dim)",
    border: "1px solid var(--color-accent)",
    borderRadius: "var(--radius-sm)",
    padding: "1px 7px",
    letterSpacing: "0.06em",
    fontWeight: 600,
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "var(--space-3)",
    padding: "var(--space-8) var(--space-6)",
    textAlign: "center",
  },
  emptyIcon: {
    fontSize: 32,
    color: "var(--color-text-muted)",
    lineHeight: 1,
  },
  emptyTitle: {
    fontSize: "var(--font-size-md)",
    fontWeight: 600,
    color: "var(--color-text-secondary)",
  },
  emptyBody: {
    fontSize: "var(--font-size-sm)",
    color: "var(--color-text-muted)",
    lineHeight: 1.7,
    maxWidth: 520,
  },
  emptyNote: {
    fontSize: "var(--font-size-xs)",
    color: "var(--color-text-muted)",
    lineHeight: 1.6,
    maxWidth: 480,
    borderTop: "1px solid var(--color-border-subtle)",
    paddingTop: "var(--space-3)",
    marginTop: "var(--space-2)",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
  },
  listNote: {
    fontSize: "var(--font-size-xs)",
    color: "var(--color-text-muted)",
    fontStyle: "italic",
    marginBottom: "var(--space-2)",
  },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "var(--space-3) var(--space-4)",
    backgroundColor: "var(--color-surface-2)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-sm)",
    gap: "var(--space-4)",
    flexWrap: "wrap",
  },
  rowLeft: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-1)",
    flex: 1,
    minWidth: 200,
  },
  rowTitle: {
    fontSize: "var(--font-size-sm)",
    fontWeight: 600,
    color: "var(--color-text-primary)",
  },
  rowMeta: {
    fontSize: "var(--font-size-xs)",
    color: "var(--color-text-muted)",
  },
  rowRight: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
    flexShrink: 0,
    flexWrap: "wrap",
  },
  statusChip: {
    fontSize: "var(--font-size-xs)",
    padding: "1px 6px",
    border: "1px solid",
    borderRadius: "var(--radius-sm)",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
};
